site_name: 'Forest Carbon Codefest ESIIL'
site_description: 'FCC 2024'
site_author: Tyler McIntosh
site_url: https://cu-esiil.github.io/forest-carbon-codefest

# Repository
repo_name: forest-carbon-codefest
repo_url: https://github.com/CU-ESIIL/forest-carbon-codefest
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Colorado Boulder'

# Page tree
nav:
  - Home: index.md
  - Collaborating on the cloud:
       - Markdown basics: collaborating-on-the-cloud/markdown_basics.md
       - Cyverse basics: collaborating-on-the-cloud/cyverse-instructions.md
       - Github basics: collaborating-on-the-cloud/github-basics.md
       - Cyverse data management: collaborating-on-the-cloud/cyverse_data_management.md
  - Additional resources
       - Code of Conduct: collaborating-on-the-cloud/code-of-conduct.md
       - Participant agreement: collaborating-on-the-cloud/participant_agreement.md
       - Cyverse hacks: collaborating-on-the-cloud/cyverse_hacks.md
       - R and Python bilingualism: collaborating-on-the-cloud/bilingualism_md.md
  - Codefest data library:
       - EPA Ecoregions: data-library/epa-ecoregions.md
       - STAC: resources/stac_mount_save.md
       - Sentinal 2 STAC example: resources/Pull_Sentinal2_l2_data.md
       - Forest Inventory Analysis Database: data-library/fia.md
       - Disturbance stack: data-library/disturbance-stack.md
       - Fire CBI: data-libary/fire-cbi.md
  - Project documentation:
       - Discussion notes: project-documentation/project-notes.md
       - Methods: project-documentation/methods.md
       - Project presentation: project-documentation/project-presentation.md
  - Publication:
       - Manuscript: resources/manuscript.md
       - Notes from readings: resources/notes_from_readings.md
       - Citations: resources/citations.md

# Configuration
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'assets/esiil_content/ESIIL_logo.png'
  favicon: 'assets/esiil_content/favicon.ico'
  # setting features for the navigation tab
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Options
extra:
  social:
    - icon: fontawesome/brands/github
    # link: https://github.com/cu-esiil/

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
